backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "people"
    label: "People"
    folder: "src/people"
    create: true
    fields:
      - { label: "Client Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["images"] }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Text", name: "text", widget: "string" }
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    fields:
      - { label: "Member Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["team"] }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Text", name: "text", widget: "string" }
      - { label: "facebook", name: "facebook", widget: "string" }
      - { label: "instagram", name: "instagram", widget: "string" }
  - name: "stars"
    label: "Stars"
    folder: "src/stars"
    create: true
    fields:
      - { label: "blockquote", name: "blockquote", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["stars"] }
      - { label: "Text", name: "text", widget: "string" }
  - name: "product"
    label: "Product"
    folder: "src/product"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["product"] }
      - { label: "Black Image", name: "imageBlack", widget: "image" }
      - { label: "Blue Image", name: "imageBlue", widget: "image" }
      - { label: "Formal Image", name: "imageCol1", widget: "image" }
      - { label: "Classic Image", name: "imageCol2", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Author Image", name: "imageAuthor", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }